### ISSUE TITLE
snapcraft command not working

### ISSUE THREAD

**Issue by forgetso** [slockit/snappy-ethereum-framework#1]
Hi,

I've tried to get this running on Ubuntu but run into several issues. First of all, running snapcraft would not pull geth - "Failed doing pull". I then changed to the development version of snapcraft and running snapcraft returned the following:

```
chris@TIGERL:~/snappy-ethereum-framework$ snapcraft
Searching for local plugin for x-script
Skipping pull files-to-copy  (already ran)
Skipping build files-to-copy  (already ran)
Skipping stage files-to-copy  (already ran)
Traceback (most recent call last):
  File "/usr/bin/snapcraft", line 33, in <module>
    snapcraft.main.main()
  File "/usr/lib/python3/dist-packages/snapcraft/main.py", line 148, in main
    args.func(args)
  File "/usr/lib/python3/dist-packages/snapcraft/cmds.py", line 98, in assemble
    snap(args)
  File "/usr/lib/python3/dist-packages/snapcraft/cmds.py", line 79, in snap
    cmd(args)
  File "/usr/lib/python3/dist-packages/snapcraft/cmds.py", line 327, in cmd
    shutil.rmtree(common.get_snapdir())
  File "/usr/lib/python3.4/shutil.py", line 468, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.4/shutil.py", line 406, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.4/shutil.py", line 406, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.4/shutil.py", line 426, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.4/shutil.py", line 424, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'libexpat.so.1.6.0'
```

Changing to sudo snapcraft allowed me to download geth and I hit a failure later on whilst building geth.

```
chris@TIGERL:~/snappy-ethereum-framework$ sudo snapcraft
Searching for local plugin for x-script
pyversions -d
Skipping pull configurator  (already ran)
pyversions -d
Skipping build configurator  (already ran)
pyversions -d
Skipping stage configurator  (already ran)
pyversions -d
Snapping configurator 
Skipping pull files-to-copy  (already ran)
Skipping build files-to-copy  (already ran)
Skipping stage files-to-copy  (already ran)
Snapping files-to-copy 
Pulling geth 
Building geth 
options.script: scripts/build_geth.sh
CWD: /home/chris/snappy-ethereum-framework
src: /home/chris/snappy-ethereum-framework/parts/geth/src
build: /home/chris/snappy-ethereum-framework/parts/geth/build
installdir: /home/chris/snappy-ethereum-framework/parts/geth/install
sh build_geth.sh /home/chris/snappy-ethereum-framework/parts/geth/install/bin
Cloning into 'go-ethereum'...
remote: Counting objects: 47959, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 47959 (delta 2), reused 0 (delta 0), pack-reused 47947
Receiving objects: 100% (47959/47959), 56.52 MiB | 3.05 MiB/s, done.
Resolving deltas: 100% (33135/33135), done.
Checking connectivity... done.
Branch develop set up to track remote branch develop from origin.
Switched to a new branch 'develop'
build/flags.sh: 13: build/flags.sh: go: not found
build/env.sh go install -v -ldflags '-X main.gitCommit8255afbc756f09c69676d79de4fcefddaa482ee8' ./cmd/geth
build/env.sh: 32: exec: go: not found
Makefile:16: recipe for target 'geth' failed
make: *** [geth] Error 127
build_geth - ERROR: Could not build geth
Failed doing build for geth: Command '['/bin/sh', '/tmp/tmpmsy6vbd0', 'sh', 'build_geth.sh', '/home/chris/snappy-ethereum-framework/parts/geth/install/bin']' returned non-zero exit status 1
```

**Comment by LefterisJP** [comment]
Hello!

First of all understand that this is a preview and is not released yet.

Secondly please read and follow [this guide](https://blog.slock.it/let-s-play-with-snappy-ethereum-816588198528#.d0c3zdho6) to have it working.

You are missing a few packages, namely golang from what I see. `sudo` should also not be needed. Make sure to use snapcraft 1.0, we have not switched to snapcraft 2.0 yet.

**Comment by forgetso** [comment]
Yes, sorry this was premature! I have since installed go. I will revert my snapcraft version, try again, and let you know the outcome

**Comment by forgetso** [comment]
Ok. So I tried snapcraft again and I have not enabled armhf architecture as 
you mentioned in your article that it "is not required for building the framework itself, but it will be needed later on for testing some of the Snaps that will be using the framework."

(1:142)$ dpkg --print-architecture
amd64

(1:143)$ dpkg --print-foreign-architectures
i386

snapcraft results in

Done building.
Run "build/bin/geth" to launch geth.
# runtime/cgo
exec: "arm-linux-gnueabihf-gcc-5": executable file not found in $PATH
build_geth - ERROR: Could not build geth-linux-arm-7
Failed doing build for geth: Command '['/bin/sh', '/tmp/tmp9de31c_u', 'sh', 'build_geth.sh', '/home/chris/snappy-ethereum-framework/parts/geth/install/bin']' returned non-zero exit status 1

I can see that geth is now built in ~/snappy-ethereum-framework/parts/geth/build/go-ethereum/build/bin. However, I don't think I have a .snap file that I can side load. Would appreciate your input.

**Comment by LefterisJP** [comment]
Yes sorry, I do have hard-coded the armhf building at the moment. Please enable it so that building can proceed.

Armhf essentially means, raspberryPI, Artik and all the other platforms we are currently testing on.

**Comment by forgetso** [comment]
Ok, np. So I've added armhf to my architectures and run sudo apt-get update.
```
(1:199)$ dpkg --print-foreign-architectures
i386
armhf
```
Which archives did you use for the architectures? My sudo apt-get update fails with 
```
W: Failed to fetch http://gb.archive.ubuntu.com/ubuntu/dists/wily-updates/universe/binary-armhf/Packages  404  Not Found [IP: 91.189.92.201 80]
```
I tried adding 
```
deb [arch=amd64,i386] http://uk.archive.ubuntu.com/ubuntu/ wily main universe
deb [arch=armel,armhf] http://ports.ubuntu.com/ubuntu-ports wily main universe
```
I've also tried 
```
deb [arch=armel,armhf] http://ports.ubuntu.com/ubuntu-ports quantal main universe
```

**Comment by LefterisJP** [comment]
Please read up on enabling armhf in Ubuntu if you want to go down that way.

But it's also possible to just get the toolchain as a package if I recall.
```
sudo apt-get install gcc-arm-linux-gnueabihf
```

**Comment by forgetso** [comment]
Thanks, Lefteris. I'll keep researching armhf in Ubuntu and try gcc-arm-linux-gnueabihf.

Which OS are you using? Debian?

**Comment by forgetso** [comment]
So installing gcc-arm-linux-gnueabihf worked on Ubuntu 15.10 x64. Thanks!

```
github.com/ethereum/go-ethereum/cmd/geth
Done building.
Run "build/bin/geth" to launch geth.
Staging geth 
Snapping geth 
pyversions -d
Skipping pull configurator  (already ran)
pyversions -d
Skipping build configurator  (already ran)
pyversions -d
Skipping stage configurator  (already ran)
pyversions -d
Snapping configurator 
pyversions -d
Snapping |
Generated 'ethereum_0.1.5_multi.snap' snap
```

Btw - the reason I am using snappy ethereum is because I intend to create a Dapp and wanted a VM that was running all of the necessary ethereum libraries. I'm not intending to test on Raspberry Pi but I was planning on setting a few of these snappy instances up in a test net scenario. Am I going down the right path or should I simply be using a full size Ubuntu VM from elsewhere?

**Comment by LefterisJP** [comment]
Happy you got it working!

Snappy-ethereum is still at beta. You can ofcourse always just use the framework but you can also simply download geth or the mist waller. Snappy ethereum is useful for IoT solution since it can run on Ubuntu Core.

**Comment by forgetso** [comment]
Right, very good point. I can just fire up several versions of geth... I guess I was just looking for a VM that came with geth etc already installed so that I could install stuff, break it, and then simply vagrant destroy afterwards.

I saw this in the code:
```
# temporarily write to /root/.ethereum until the introduction of a common "shared"
# directory for all versions of a snap which is expected to happen in 16.xx version.
```
Will this allow multiple versions of geth to run from the same chain data? Or will each snappy ethereum instance continue to use individual instances of the chain data (approx. 8Gb each time, or whatever it is by now)?

**Comment by LefterisJP** [comment]
@forgetso No no, it's quite different. The whole point of snappy is that it allows for transactional updates. You can upgrade a package, say the ethereum framework, and then if something goes bad you can revert to the previous version.

At the moment snappy allows for no way to have common data directories between versions. Which means that if we don't have this "hack" that I have there, every time you update the framework (sideloading a new version counts as updating) a copy of the whole data directory including the blockchain will be made. This way the system will be able to revert in case of problems.

Of course this is bad, since we definitely don't want to copy the whole blockchain at each update. The developers of snappy Ubuntu are aware of this problem and will create in the future a directory that will be shared between all versions of a package. At that time this hack will go away.
